// app/layout.js
import { Varela } from "next/font/google";
import './globals.css';
import { Analytics } from "@vercel/analytics/react"

const varela = Varela({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={varela.className}>
        <main>
          {children}
          <Analytics />
        </main>
      </body>
    </html>
  );
}